In [1]:
import pandas as pd
df = pd.read_csv("datasets\IMDB Dataset.csv")

In [2]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## lowercase

In [3]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [4]:
df['review'] = df['review'].str.lower()

In [5]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

## remove html text

In [6]:
import re
def remove_html(text):
    pattern = re.compile(r'<.*?>')
    return pattern.sub(r'', text)

In [7]:
text = df['review'][1]

In [8]:
remove_html(text)

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [9]:
df['review'] = df['review'].apply(remove_html)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

## remove URL

In [10]:
def remove_url(text):
    pattern = re.compile(r'http\S+|www\.\S+')
    return pattern.sub('', text)

In [11]:
text = 'alfksdkj https://www.youtube.com/watch?v=6C0sLtw5ctc&list=PLKnIA16_RmvZo7fp5kkIth6nRTeQQsjfX&index=3&t=3790s jflsk'

In [12]:
text = remove_url(text)
text

'alfksdkj  jflsk'

In [13]:
df['review'] = df['review'].apply(remove_url)

## remove multiple spaces

In [14]:
def remove_multi_space(text):
    pattern = re.compile(r'\s+')
    return pattern.sub(' ', text)

In [15]:
text = 'abdfs lsdkfj  lskdjfk   lsdkfjk      sldkfjl'
remove_multi_space(text)

'abdfs lsdkfj lskdjfk lsdkfjk sldkfjl'

In [16]:
df['review'] = df['review'].apply(remove_multi_space)

## remove punctuations

In [17]:
import string
#slower method
def rem_punc1(text):
    for char in text:
        if char in string.punctuation:
            text = text.replace(char, '')
    return text


import time
start_time = time.time()
df['review'].apply(rem_punc1)
time_taken1 = time.time() - start_time
time_taken1

5.036501169204712

In [18]:
#faster method
def rem_punc2(text):
    return text.translate(str.maketrans('','',string.punctuation))


import time
start_time = time.time()
df['review'].apply(rem_punc2)
time_taken2 = time.time() - start_time
time_taken2

1.1088745594024658

In [19]:
time_taken1/time_taken2

4.5419936155075185

In [20]:
df['review'] = df['review'].apply(rem_punc2)

In [21]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## replace chat words with proper words

In [22]:
chat_abbreviations = {
    # Numbers / Symbols
    "?4U": "I have a question for you",
    "<3": "Love / Heart",
    "2": "To",
    "2mrw": "Tomorrow",
    "2nite": "Tonight",
    "4": "For",
    "4ever": "Forever",
    "121": "One-to-one",
    "143": "I love you",
    "411": "Information",
    "14AA41": "One for all and all for one",
    "86": "Over / Out of",

    # A
    "AAF": "As a friend",
    "AFAIC": "As far as I'm concerned",
    "AFAIK": "As far as I know",
    "AFAIR": "As far as I remember/recall",
    "AFK": "Away from keyboard",
    "AKA": "Also known as",
    "AMA": "Ask me anything",
    "ASL": "Age/Sex/Location",
    "A/S/L": "Age/Sex/Location",
    "ASAP": "As soon as possible",
    "ASIG": "And so it goes",
    "ATM": "At the moment",
    "AYS": "Are you serious?",
    "AYT": "Are you there?",
    "AF": "As f**k",

    # B
    "B2W": "Back to work",
    "B4": "Before",
    "B4N": "Bye for now",
    "BAK": "Back at keyboard",
    "BB": "Baby / Bye-bye",
    "BBIAB": "Be back in a bit",
    "BBL": "Be back later",
    "BBS": "Be back soon",
    "BC": "Because",
    "BF": "Boyfriend",
    "BFF": "Best friends forever",
    "BFN": "Bye for now",
    "BLNT": "Better luck next time",
    "BM&Y": "Between me and you",
    "BME": "Based on my experience",
    "BRB": "Be right back",
    "BTW": "By the way",
    "BWL": "Bursting with laughter",
    "B/C": "Because",
    "B/W": "Between",

    # C
    "CMB": "Call me back",
    "CMIIW": "Correct me if I'm wrong",
    "CMON": "Come on",
    "CR8": "Create",
    "CTC": "Care to chat?",
    "CTN": "Can't talk now",
    "CU": "See you",
    "CU L8R": "See you later",
    "CUZ": "Because",
    "COS": "Because",
    "CWYL": "Chat with you later",
    "CYA": "See ya",
    "CYE": "Check your email",

    # D
    "DC": "Disconnected",
    "DI": "Download",
    "DIY": "Do it yourself",
    "DKDC": "Don't know and don't care",
    "DM": "Direct message",
    "DW": "Dear wife / Don't worry",

    # E
    "EOD": "End of day",
    "ETA": "Estimated time of arrival",

    # F
    "F2F": "Face-to-face",
    "FAQ": "Frequently asked questions",
    "FB": "Facebook",
    "FF": "Follow Friday",
    "FTW": "For the win",
    "FWIW": "For what it's worth",
    "FYI": "For your information",
    "FYEO": "For your eyes only",

    # G
    "G2G": "Got to go",
    "GB": "Goodbye",
    "GF": "Girlfriend",
    "GG": "Good game / Gotta go",
    "GJ": "Good job",
    "GL": "Good luck",
    "GMV": "Got my vote",
    "GR8": "Great",
    "GTG": "Got to go",

    # H
    "HBD": "Happy birthday",
    "HMU": "Hit me up",
    "HTH": "Hope this helps",
    "HW": "Homework",

    # I
    "IAC": "In any case",
    "IC": "I see",
    "IDC": "I don't care",
    "IDK": "I don't know",
    "IIRC": "If I remember correctly",
    "IK": "I know",
    "IKR": "I know, right?",
    "ILY": "I love you",
    "IM": "Instant message",
    "IMHO": "In my humble opinion",
    "IMO": "In my opinion",
    "IOW": "In other words",
    "IRL": "In real life",

    # J
    "JK": "Just kidding",
    "J/K": "Just kidding",

    # K
    "K": "OK",

    # L
    "L8R": "Later",
    "LMAO": "Laughing my a** off",
    "LMFAO": "Laughing my f***ing a** off",
    "LMK": "Let me know",
    "LOL": "Laugh out loud",

    # M
    "MCM": "Man crush Monday",
    "M/F": "Male or female?",
    "MINS": "Minutes",
    "MSG": "Message",

    # N
    "NGL": "Not gonna lie",
    "NP": "No problem",
    "NTN": "No thanks needed",
    "NVM": "Never mind",
    "NV": "Nevermind",

    # O
    "OFC": "Of course",
    "OIC": "Oh, I see",
    "OMG": "Oh my God",
    "OMW": "On my way",
    "OT": "Off topic",
    "OTW": "On the way",

    # P
    "P2P": "Person-to-person",
    "PC": "Personal computer",
    "PLS": "Please",
    "PLZ": "Please",
    "PM": "Private message",
    "POS": "Parent over shoulder",
    "PPL": "People",

    # Q
    "QT": "Cutie",

    # R
    "RE": "Regarding",
    "ROFL": "Rolling on the floor laughing",
    "RUOK": "Are you okay?",

    # S
    "SMP": "Social media platform",
    "SMH": "Shaking my head",
    "SRY": "Sorry",
    "SUP": "What's up?",

    # T
    "TBH": "To Be Honest",
    "TC": "Take care",
    "TGIF": "Thank goodness it's Friday",
    "THX": "Thanks",
    "THNX": "Thanks",
    "TTFN": "Ta ta for now",
    "TTYL": "Talk to you later",
    "TTYRS": "Talk to you real soon",
    "TTYS": "Talk to you soon",
    "TTUL": "Talk to you later",
    "TTG": "Time to go",
    "TXT": "Text",
    "TY": "Thank you",
    "TYLE": "Took you long enough",
    "TYT": "Take your time",
    "TYVM": "Thank you very much",
    "TYVL": "Thank you very little",
    "TWIMC": "To whom it may concern",
    "TTBOMK": "To the best of my knowledge",
    "TRDMC": "Tears running down my cheeks",

    # U
    "U": "You",
    "U2": "You too",
    "UR": "Your / You're",

    # W
    "W/": "With",
    "W/O": "Without",
    "WRU": "Where are you?",
    "WCW": "Woman crush Wednesday",

    # X
    "XO": "Hugs and kisses / Love",
    "XOXO": "Hugs and kisses",

    # Y
    "YOLO": "You only live once",
    "YW": "You're welcome",

    # Z
    "ZUP": "What's up?",
    "ZZZ": "Tired / Bored / Sleeping",
}

In [23]:
def correct_chat_words(text):
    new_text = []
    for word in text.split():
        word = word.replace(',','')
        word = word.upper()
        if word in chat_abbreviations:
            new_text.append(chat_abbreviations[word])
        else:
            new_text.append(word)
    return " ".join(new_text).lower()

In [24]:
txt = 'Omg tbh, I was AFK when the TBH DM dropped, but IMO it’s NGL totally lit RN ngl'

In [25]:
correct_chat_words(txt)

'oh my god to be honest i was away from keyboard when the to be honest direct message dropped but in my opinion it’s not gonna lie totally lit rn not gonna lie'

In [26]:
df['review'] = df['review'].apply(correct_chat_words)

## spelling correction

In [27]:
# slow method
from textblob import TextBlob
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'
text_blob = TextBlob(incorrect_text)
text_blob.correct().string

'certain conditions during several generations are modified in the same manner.'

In [28]:
# df['review'] = df['review'].apply(lambda x: str(TextBlob(x).correct()))

## Remove stop words :: a, an, the, is, am, are, to, with, for, of etc.

In [29]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dex\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [30]:
from nltk.corpus import stopwords

In [31]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [32]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    return " ".join(new_text)

In [33]:
# df['review'] = df['review'].apply(remove_stopwords)

## Handle Emojis : remove emoji OR replace emoji

In [34]:
# Method 1: remove emojis
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [35]:
df['review'] = df['review'].apply(remove_emoji)

In [37]:
# Method 2: replace emojis with their text
import emoji
emoji_text = 'Whether you are expressing excitement 🤩, sending love 🥰, or laughing until you cry 😭'
emoji.demojize(emoji_text)    #gives text in place of emoji

'Whether you are expressing excitement :star-struck:, sending love :smiling_face_with_hearts:, or laughing until you cry :loudly_crying_face:'

## Tokenization

In [38]:
# word tokenization
text1 = 'I am going to Delhi'
text1.split()

['I', 'am', 'going', 'to', 'Delhi']

In [39]:
# sentence tokenization
text2 = 'I am going to Delhi. I will stay there for 3 days. Let\'s hope the trip to be great.'
text2.split('.')

['I am going to Delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great",
 '']

In [44]:
# split function splits on one character only.
# what if sentences end with . ? ! 
# to overcome this, use REGEX
import re
text3 = 'I am going to Delhi? I will stay there for 3 days! Let\'s hope the trip to be great.'
sentences = re.compile('[.!?] ').split(text3)
sentences

['I am going to Delhi',
 'I will stay there for 3 days',
 "Let's hope the trip to be great."]

In [45]:
import re
text4 = 'I am going to delhi!'
tokens = re.findall("[\w]+", text4)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [49]:
# Tokenization using NLTK
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dex\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [50]:
from nltk.tokenize import word_tokenize, sent_tokenize
text5 = 'I am going to Delhi? I will stay there for 3 days! Let\'s hope the trip to be great.'

In [51]:
word_tokenize(text5)

['I',
 'am',
 'going',
 'to',
 'Delhi',
 '?',
 'I',
 'will',
 'stay',
 'there',
 'for',
 '3',
 'days',
 '!',
 'Let',
 "'s",
 'hope',
 'the',
 'trip',
 'to',
 'be',
 'great',
 '.']

In [52]:
sent_tokenize(text5)

['I am going to Delhi?',
 'I will stay there for 3 days!',
 "Let's hope the trip to be great."]

In [57]:
# Tokenization using Spacy
import spacy
!python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")    #load english dictionary

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     -- ------------------------------------- 0.8/12.8 MB 7.5 MB/s eta 0:00:02
     ----- ---------------------------------- 1.8/12.8 MB 4.4 MB/s eta 0:00:03
     ------- -------------------------------- 2.4/12.8 MB 4.3 MB/s eta 0:00:03
     --------- ------------------------------ 3.1/12.8 MB 3.8 MB/s eta 0:00:03
     ----------- ---------------------------- 3.7/12.8 MB 3.8 MB/s eta 0:00:03
     -------------- ------------------------- 4.7/12.8 MB 3.8 MB/s eta 0:00:03
     ----------------- ---------------------- 5.5/12.8 MB 3.9 MB/s eta 0:00:02
     ------------------- -------------------- 6.3/12.8 MB 3.9 MB/s eta 0:00:02
     ---------------------- ----------------- 7.1/12.8 MB 3.9 MB/s eta 0:00:02
     ------------------------ --------------- 7.9/12.8 MB 3.9 MB/s eta 0:00:02
     --------------------------- ------------ 8.7/12.8 MB 3.9 MB/s eta 0:00:02
     ----------------------------- ---------- 9.4/12.8 MB 3.9 MB/s eta 0:00:01
     -------------------------------- ------- 10.5/12.8 MB 3.9 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.8 MB 3.9 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 3.9 MB/s  0:00:03
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [58]:
doc = nlp(text5)
doc

I am going to Delhi? I will stay there for 3 days! Let's hope the trip to be great.

In [59]:
for token in doc:
    print(token)

I
am
going
to
Delhi
?
I
will
stay
there
for
3
days
!
Let
's
hope
the
trip
to
be
great
.

## Stemming - root form of the word

In [60]:
from nltk.stem.porter import PorterStemmer

In [61]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [62]:
text = 'walk walks walking walked'
stem_words(text)

'walk walk walk walk'

In [63]:
text = 'The incredibly incredible stories of the britishers is unadmirable.'
stem_words(text)

'the incred incred stori of the british is unadmirable.'

In [66]:
# this shows that STEMMING is rule based, so the root words are incorrect
# to overcome this, use LEMMATIZATION (slower but correct)
# LEMMATIZATION gets the root words from Lexical Dictionary

## Lemmatization - correct root form of the words

In [70]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Dex\AppData\Roaming\nltk_data...

True

In [72]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

text = 'He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun.'
punctuations = "?:!.,;"
sentence_words = nltk.word_tokenize(text)

for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

In [74]:
sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))
#pos='v' - verb form of root word

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun