In [1]:
%load_ext cudf.pandas
%load_ext cuml.accel

import cudf
import pandas as pd
import cupy as cp
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import re
from collections import Counter

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [37]:
df_train = pd.read_csv('datasets/Quora Questions Pair Dataset/train_preprocessed.csv')
print(type(df_train))
df_train.sample(3)

<class 'pandas.core.frame.DataFrame'>

,question1,question2,is_duplicate
257124,what are some examples of warm blooded and col...,what are the characteristics of warm blooded a...,0
97289,what is a year year swap rate used to benchmar...,what does a × at the moment receiver european ...,0
349031,how can i overcome my porn addiction,how do i get over my porn addiction,1

In [38]:
def tokenize(text):
    return text.split()

In [39]:
all_tokens = []
for col in ['question1', 'question2']:
    for row in df_train[col]:
        all_tokens.extend(tokenize(row))
print(f"Corpus size: {len(all_tokens)}")

Corpus size: 9016420

In [40]:
#get all the words with the number of times they repeat
counter = Counter(all_tokens)
counter

Counter({'the': 377839,
         'what': 324363,
         'is': 289059,
         'i': 223939,
         'how': 220801,
         'a': 212917,
         'in': 212427,
         'to': 206012,
         'do': 169383,
         'of': 159909,
         'are': 149286,
         'and': 134042,
         'can': 114060,
         'for': 104507,
         'you': 96125,
         'my': 86135,
         'why': 84021,
         'it': 71495,
         'best': 70586,
         'on': 60733,
         'does': 59436,
         'have': 44876,
         'or': 44718,
         'which': 43959,
         'be': 43843,
         'if': 43795,
         'some': 41677,
         'that': 40702,
         'with': 39727,
         'get': 39544,
         'should': 39541,
         'not': 38753,
         'an': 37008,
         'from': 35244,
         'your': 34025,
         'india': 29512,
         'will': 29419,
         's': 28597,
         'people': 26386,
         'when': 26215,
         'who': 26074,
         'like': 25634,
         'at': 25625,
         'good': 24866,
         'would': 24134,
         'there': 23660,
         'as': 22762,
         'about': 21145,
         'am': 20879,
         'between': 20293,
         'one': 20010,
         'did': 19582,
         'most': 18982,
         'we': 18515,
         'quora': 18220,
         'make': 18199,
         'way': 18130,
         'where': 17431,
         'by': 17315,
         'any': 16881,
         'was': 16785,
         'me': 16560,
         'life': 16498,
         'eyes': 16014,
         'so': 15957,
         'they': 15609,
         'tears': 15176,
         'after': 15135,
         'this': 14893,
         'money': 14582,
         'know': 13780,
         'has': 13716,
         'difference': 13388,
         'learn': 13083,
         'new': 12436,
         'use': 12374,
         'much': 12368,
         'someone': 12026,
         'their': 11776,
         'think': 11501,
         'many': 11458,
         'work': 11259,
         'all': 11224,
         'indian': 10793,
         'trump': 10630,
         'than': 10627,
         'more': 10587,
         'ever': 10576,
         'find': 10565,
         'without': 10018,
         'but': 9926,
         'world': 9919,
         'become': 9910,
         'start': 9883,
         'online': 9761,
         'better': 9694,
         'first': 9691,
         'other': 9684,
         'out': 9534,
         'want': 9532,
         'year': 9350,
         'mean': 8745,
         'job': 8693,
         'us': 8535,
         'english': 8524,
         'up': 8278,
         'into': 8241,
         'could': 8161,
         'he': 8130,
         'feel': 8004,
         'love': 7965,
         'take': 7813,
         'possible': 7767,
         'day': 7697,
         'things': 7288,
         'questions': 7274,
         'go': 7232,
         'notes': 7157,
         'phone': 7088,
         'were': 7056,
         'buy': 6919,
         'really': 6917,
         'ways': 6913,
         'engineering': 6899,
         'person': 6892,
         'account': 6859,
         'weight': 6849,
         'used': 6793,
         'donald': 6741,
         'long': 6603,
         'google': 6550,
         'them': 6539,
         'old': 6489,
         'girl': 6487,
         'number': 6339,
         'being': 6293,
         'her': 6281,
         'improve': 6226,
         'using': 6156,
         'his': 6058,
         'need': 6013,
         'business': 5994,
         'facebook': 5988,
         'books': 5972,
         'sex': 5959,
         'language': 5888,
         'stop': 5863,
         'lose': 5853,
         'movie': 5795,
         'different': 5752,
         'thing': 5730,
         'black': 5719,
         'been': 5655,
         'book': 5574,
         'free': 5555,
         'see': 5546,
         'now': 5538,
         'years': 5488,
         'just': 5480,
         'war': 5464,
         'going': 5461,
         'compare': 5421,
         'question': 5397,
         'no': 5379,
         'programming': 5296,
         'still': 5288,
         'had': 5223,
         'only': 5138,
         'instagram': 5111,
         'president': 5091,
         'help': 5087,
         'change': 5067,
         'company': 5061,
         'its': 5027,
         'happen': 5022,
         'movies': 5021,
         'c': 5017,
         'before': 5007,
         'women': 5000,
         'app': 4986,
         'she': 4940,
         'real': 4867,
         'college': 4862,
         'over': 4828,
         'prepare': 4798,
         'rs': 4789,
         'under': 4764,
         'android': 4752,
         'win': 4748,
         'examples': 4707,
         'computer': 4684,
         'clinton': 4641,
         'country': 4629,
         'live': 4604,
         'back': 4582,
         'while': 4575,
         'website': 4560,
         'iphone': 4560,
         'ask': 4552,
         'b': 4526,
         'cannot': 4515,
         'learning': 4513,
         'data': 4480,
         'system': 4460,
         'important': 4450,
         'bad': 4440,
         'our': 4408,
         'study': 4327,
         'top': 4285,
         'made': 4280,
         'hillary': 4278,
         'increase': 4254,
         'through': 4237,
         'same': 4236,
         'school': 4228,
         'science': 4202,
         'read': 4192,
         'two': 4098,
         'software': 4061,
         'government': 4008,
         'earn': 4000,
         'water': 3992,
         'math': 3992,
         'card': 3990,
         'during': 3986,
         'men': 3862,
         'student': 3856,
         'mobile': 3854,
         'high': 3842,
         'car': 3813,
         'say': 3810,
         'x': 3797,
         'exam': 3788,
         'energy': 3763,
         'name': 3749,
         'word': 3731,
         'give': 3722,
         'university': 3719,
         'anyone': 3709,
         'getting': 3676,
         'earth': 3634,
         'companies': 3562,
         'right': 3553,
         'true': 3518,
         'china': 3509,
         'days': 3503,
         'average': 3466,
         'home': 3455,
         'k': 3450,
         'laptop': 3427,
         'then': 3424,
         'doing': 3419,
         'web': 3409,
         'come': 3393,
         'career': 3378,
         'friend': 3377,
         'even': 3352,
         'hair': 3340,
         'tell': 3327,
         'com': 3311,
         'look': 3302,
         'interview': 3288,
         'answer': 3288,
         'social': 3280,
         'him': 3263,
         'own': 3262,
         'video': 3261,
         'bank': 3254,
         'travel': 3238,
         'usa': 3223,
         'friends': 3220,
         'meaning': 3208,
         'write': 3207,
         'guy': 3203,
         'safe': 3202,
         'man': 3201,
         'th': 3182,
         'watch': 3167,
         'youtube': 3158,
         'students': 3142,
         'off': 3110,
         'cost': 3108,
         'password': 3101,
         'pakistan': 3098,
         'non': 3094,
         'done': 3087,
         'eat': 3082,
         'working': 3074,
         'relationship': 3069,
         'rupee': 3065,
         'experience': 3054,
         'place': 3045,
         'happens': 3041,
         'food': 3030,
         'girls': 3029,
         'game': 3018,
         'tv': 3016,
         'rid': 3014,
         'big': 3009,
         'having': 3008,
         'very': 3001,
         'human': 2943,
         'mind': 2942,
         'service': 2942,
         'whatsapp': 2925,
         'play': 2919,
         'countries': 2913,
         'favorite': 2890,
         'major': 2875,
         'keep': 2859,
         'future': 2850,
         'history': 2849,
         'employees': 2841,
         'age': 2805,
         'affect': 2796,
         'end': 2784,
         'download': 2774,
         'tech': 2767,
         'white': 2766,
         'engineer': 2760,
         'state': 2759,
         'too': 2756,
         'e': 2756,
         'believe': 2745,
         'great': 2741,
         'process': 2740,
         'tips': 2736,
         'skills': 2724,
         'modi': 2724,
         'myself': 2717,
         'last': 2713,
         'exist': 2709,
         'effects': 2707,
         'election': 2707,
         'body': 2705,
         'every': 2701,
         'g': 2698,
         'chinese': 2695,
         'test': 2684,
         'email': 2680,
         'java': 2680,
         'support': 2678,
         'next': 2667,
         'against': 2665,
         'delhi': 2663,
         'marketing': 2657,
         'class': 2643,
         'mechanical': 2642,
         'create': 2641,
         'god': 2639,
         'differences': 2637,
         'month': 2624,
         'girlfriend': 2623,
         'internet': 2620,
         'hard': 2614,
         'places': 2611,
         'makes': 2599,
         'interesting': 2593,
         'states': 2583,
         'got': 2578,
         'making': 2566,
         'american': 2563,
         'police': 2559,
         'music': 2558,
         'visit': 2538,
         'united': 2504,
         'these': 2486,
         'windows': 2486,
         'worth': 2472,
         'pay': 2467,
         'power': 2467,
         'market': 2454,
         'never': 2443,
         'song': 2429,
         'salary': 2416,
         'around': 2404,
         'woman': 2398,
         'control': 2391,
         'each': 2390,
         'actually': 2383,
         'america': 2366,
         'course': 2357,
         'series': 2347,
         'culture': 2346,
         'answers': 2342,
         'code': 2340,
         'looking': 2339,
         'gmail': 2332,
         'available': 2320,
         'something': 2314,
         'fat': 2304,
         'always': 2292,
         'considered': 2289,
         'another': 2266,
         'months': 2265,
         'hotel': 2265,
         'today': 2264,
         'common': 2262,
         'self': 2249,
         'economy': 2243,
         'writing': 2242,
         'light': 2238,
         'apply': 2238,
         'universities': 2235,
         'site': 2233,
         'development': 2233,
         'delete': 2232,
         'die': 2224,
         'jobs': 2213,
         'parents': 2201,
         'mba': 2193,
         'd': 2181,
         'per': 2172,
         'cat': 2152,
         'open': 2145,
         'happened': 2143,
         'idea': 2135,
         'type': 2131,
         'such': 2130,
         'score': 2130,
         'problem': 2128,
         'deal': 2124,
         'kind': 2123,
         'services': 2121,
         'universe': 2111,
         'review': 2105,
         'speed': 2099,
         'show': 2093,
         'behind': 2090,
         'build': 2088,
         'list': 2083,
         'dark': 2082,
         'design': 2076,
         'hack': 2075,
         'note': 2074,
         'purpose': 2073,
         'living': 2073,
         'able': 2071,
         'worst': 2068,
         'space': 2065,
         'bangalore': 2061,
         'songs': 2058,
         'well': 2052,
         'post': 2049,
         'education': 2044,
         'near': 2035,
         'games': 2029,
         'period': 2027,
         'family': 2021,
         'seen': 2021,
         'because': 2013,
         'presidential': 2012,
         'reason': 2011,
         'date': 2006,
         'differ': 2005,
         'reduce': 2001,
         'popular': 2000,
         'digital': 1999,
         'wrong': 1999,
         'law': 1998,
         'run': 1998,
         'cause': 1998,
         'call': 1993,
         'current': 1991,
         'asked': 1991,
         'private': 1986,
         'height': 1982,
         'instead': 1981,
         'websites': 1981,
         'civil': 1980,
         'technology': 1974,
         'majors': 1973,
         'join': 1969,
         'degree': 1962,
         'management': 1958,
         'loss': 1953,
         'apple': 1952,
         'air': 1947,
         'program': 1942,
         'easily': 1935,
         'boyfriend': 1930,
         'apps': 1923,
         'international': 1917,
         'order': 1917,
         'hate': 1915,
         'traffic': 1913,
         'sentence': 1907,
         'ca': 1902,
         'facts': 1897,
         'sleep': 1893,
         'public': 1892,
         'based': 1891,
         'biggest': 1890,
         'times': 1890,
         'stay': 1884,
         'down': 1880,
         'center': 1876,
         'city': 1875,
         'main': 1875,
         'pregnant': 1875,
         'canada': 1868,
         'causes': 1865,
         'search': 1864,
         'visa': 1860,
         'currency': 1843,
         'choose': 1837,
         'both': 1836,
         'ms': 1835,
         'sites': 1835,
         'iit': 1831,
         'compared': 1822,
         'benefits': 1821,
         'indians': 1820,
         'media': 1817,
         'python': 1817,
         'death': 1812,
         'add': 1808,
         'less': 1806,
         'gain': 1805,
         'small': 1805,
         'also': 1804,
         'child': 1800,
         'part': 1790,
         'drug': 1790,
         'recover': 1785,
         'face': 1785,
         'california': 1784,
         'machine': 1781,
         'wear': 1780,
         'house': 1775,
         'startup': 1773,
         'plan': 1770,
         'decision': 1763,
         'move': 1761,
         'successful': 1759,
         'fast': 1753,
         'fall': 1752,
         'battle': 1748,
         'jee': 1747,
         'videos': 1746,
         'products': 1743,
         'story': 1742,
         'stock': 1739,
         'foreign': 1739,
         'terms': 1735,
         'dog': 1730,
         'remove': 1730,
         'level': 1724,
         'legal': 1723,
         'given': 1722,
         'health': 1716,
         'value': 1715,
         'amazon': 1710,
         'ban': 1710,
         'overcome': 1709,
         'humans': 1707,
         'normal': 1706,
         'medical': 1705,
         'preparation': 1699,
         'product': 1693,
         'found': 1693,
         'views': 1690,
         'invest': 1687,
         'banning': 1685,
         'point': 1674,
         'created': 1663,
         'profile': 1662,
         'project': 1658,
         'etc': 1656,
         'form': 1655,
         'vote': 1653,
         'ones': 1651,
         'uk': 1644,
         'called': 1640,
         'coaching': 1634,
         'rate': 1634,
         'again': 1625,
         'theory': 1623,
         'solar': 1621,
         'known': 1621,
         'gate': 1613,
         'snapchat': 1610,
         'drive': 1607,
         'ideas': 1603,
         'easiest': 1602,
         'research': 1601,
         'side': 1595,
         'physics': 1593,
         'porn': 1593,
         'alcohol': 1593,
         'speak': 1591,
         'hours': 1590,
         'effect': 1582,
         'grow': 1578,
         'must': 1575,
         'yourself': 1575,
         'group': 1571,
         'matter': 1559,
         'week': 1550,
         'send': 1548,
         'others': 1547,
         'advice': 1538,
         'single': 1534,
         'credit': 1534,
         'application': 1531,
         'australia': 1531,
         'quality': 1528,
         'ias': 1527,
         'sell': 1526,
         'talk': 1525,
         'anything': 1525,
         'easy': 1522,
         'full': 1521,
         'night': 1518,
         'follow': 1518,
         'view': 1518,
         'germany': 1517,
         'correct': 1516,
         'cons': 1516,
         'pros': 1515,
         'faster': 1507,
         'russia': 1506,
         'information': 1504,
         'bollywood': 1500,
         'sydney': 1498,
         'famous': 1498,
         'lot': 1498,
         'required': 1495,
         'children': 1487,
         'guys': 1486,
         'solve': 1485,
         'green': 1478,
         'marks': 1475,
         'improvement': 1475,
         'message': 1467,
         'size': 1466,
         'field': 1464,
         'star': 1463,
         'moment': 1463,
         'mumbai': 1463,
         'low': 1462,
         'put': 1461,
         'daily': 1456,
         'messages': 1456,
         'file': 1455,
         'distance': 1454,
         'advantages': 1454,
         'courses': 1453,
         'kill': 1449,
         'institute': 1448,
         'options': 1444,
         'south': 1444,
         'short': 1443,
         'studying': 1440,
         'desert': 1440,
         'pro': 1438,
         'security': 1437,
         'marriage': 1436,
         'rupees': 1435,
         'similar': 1433,
         'cell': 1430,
         'left': 1428,
         'languages': 1426,
         'tax': 1420,
         'suicide': 1417,
         'force': 1410,
         'effective': 1408,
         't': 1407,
         'provider': 1407,
         'happy': 1406,
         'problems': 1406,
         'general': 1402,
         'avoid': 1397,
         'simple': 1395,
         'started': 1395,
         'industry': 1390,
         'those': 1387,
         'investment': 1385,
         'n': 1384,
         'healthy': 1382,
         'source': 1381,
         'developer': 1379,
         'blood': 1378,
         'term': 1377,
         'function': 1377,
         'sim': 1376,
         'safety': 1376,
         'lost': 1375,
         'deleted': 1373,
         'suitable': 1368,
         'uber': 1363,
         'dream': 1355,
         'impact': 1354,
         'set': 1354,
         'three': 1350,
         'mass': 1349,
         'says': 1348,
         'pc': 1345,
         'exactly': 1341,
         'often': 1340,
         'colleges': 1334,
         'iq': 1333,
         'photos': 1332,
         'ex': 1329,
         'likes': 1324,
         'blog': 1324,
         'words': 1323,
         'jio': 1322,
         'area': 1322,
         'oil': 1321,
         'beautiful': 1320,
         'brain': 1315,
         'care': 1310,
         'turn': 1309,
         'develop': 1309,
         'graduate': 1304,
         'text': 1304,
         'fix': 1298,
         'types': 1292,
         'cold': 1292,
         'model': 1291,
         'chemical': 1287,
         'electrical': 1286,
         'heard': 1280,
         'across': 1280,
         'party': 1276,
         'page': 1276,
         'married': 1275,
         'few': 1273,
         'reasons': 1273,
         'japan': 1268,
         'engine': 1268,
         'picture': 1267,
         'price': 1266,
         'dogs': 1264,
         'net': 1262,
         'japanese': 1260,
         'gay': 1259,
         'male': 1255,
         'proposed': 1255,
         'share': 1254,
         'leave': 1253,
         'office': 1252,
         'numbers': 1250,
         'pass': 1250,
         'contact': 1250,
         'training': 1247,
         'past': 1247,
         'second': 1245,
         'address': 1245,
         'understand': 1244,
         'check': 1243,
         'store': 1241,
         'north': 1239,
         'enough': 1236,
         'team': 1234,
         'eating': 1233,
         'fight': 1231,
         'female': 1229,
         'offer': 1229,
         'line': 1225,
         'hindi': 1225,
         'coming': 1222,
         'letter': 1222,
         'red': 1221,
         'obama': 1220,
         'late': 1220,
         'macbook': 1220,
         'exams': 1220,
         'ios': 1219,
         'religion': 1219,
         'related': 1218,
         'basic': 1212,
         'access': 1210,
         'network': 1208,
         'chances': 1207,
         'boy': 1204,
         'said': 1202,
         'wife': 1200,
         'samsung': 1200,
         'americans': 1197,
         'taking': 1193,
         'once': 1191,
         'inr': 1189,
         'prime': 1187,
         'moon': 1185,
         'quickly': 1185,
         'topics': 1183,
         'calculate': 1180,
         'british': 1179,
         'political': 1177,
         'precautions': 1172,
         'hyderabad': 1171,
         'away': 1170,
         'meet': 1169,
         'personal': 1168,
         'balance': 1168,
         'gold': 1167,
         'everything': 1165,
         'handling': 1165,
         'film': 1163,
         'county': 1163,
         'penis': 1163,
         'narendra': 1162,
         'everyone': 1161,
         'national': 1159,
         'changed': 1155,
         'users': 1154,
         'smart': 1153,
         'convert': 1153,
         'mix': 1152,
         'chance': 1148,
         'panel': 1143,
         'since': 1141,
         'pune': 1141,
         'drink': 1139,
         'depression': 1138,
         'installation': 1137,

In [41]:
# build vocab of all the words with 5 or more occurences
MIN_COUNT = 4
vocab = ['<pad>','<unk>'] + [w for w,c in counter.items() if c >= MIN_COUNT]
vocab

['<pad>',
 '<unk>',
 'what',
 'is',
 'the',
 'step',
 'by',
 'guide',
 'to',
 'invest',
 'in',
 'share',
 'market',
 'india',
 'story',
 'of',
 'kohinoor',
 'koh',
 'i',
 'noor',
 'diamond',
 'how',
 'can',
 'increase',
 'speed',
 'my',
 'internet',
 'connection',
 'while',
 'using',
 'a',
 'vpn',
 'why',
 'am',
 'mentally',
 'very',
 'lonely',
 'solve',
 'it',
 'which',
 'one',
 'dissolve',
 'water',
 'sugar',
 'salt',
 'methane',
 'and',
 'carbon',
 'di',
 'oxide',
 'astrology',
 'capricorn',
 'sun',
 'cap',
 'moon',
 'rising',
 'does',
 'that',
 'say',
 'about',
 'me',
 'should',
 'buy',
 'tiago',
 'be',
 'good',
 'geologist',
 'when',
 'do',
 'you',
 'use',
 'instead',
 'motorola',
 'company',
 'hack',
 'charter',
 'method',
 'find',
 'separation',
 'slits',
 'fresnel',
 'read',
 'youtube',
 'comments',
 'make',
 'physics',
 'easy',
 'learn',
 'was',
 'your',
 'first',
 'sexual',
 'experience',
 'like',
 'are',
 'laws',
 'change',
 'status',
 'from',
 'student',
 'visa',
 'green',
 'card',
 'us',
 'they',
 'compare',
 'immigration',
 'canada',
 'would',
 'trump',
 'presidency',
 'mean',
 'for',
 'current',
 'international',
 'master’s',
 'students',
 'on',
 'an',
 'f',
 'manipulation',
 'girls',
 'want',
 'friends',
 'with',
 'guy',
 'reject',
 'so',
 'many',
 'quora',
 'users',
 'posting',
 'questions',
 'readily',
 'answered',
 'google',
 'best',
 'digital',
 'marketing',
 'institution',
 'banglore',
 'rockets',
 'look',
 'white',
 'causing',
 'someone',
 'jealous',
 'not',
 'ask',
 'much',
 'kv',
 'hp',
 'every',
 'tears',
 'eyes',
 'at',
 'clock',
 'numbers',
 'same',
 'some',
 'tips',
 'making',
 'through',
 'job',
 'interview',
 'process',
 'medicines',
 'web',
 'application',
 'society',
 'place',
 'too',
 'importance',
 'sports',
 'way',
 'money',
 'online',
 'prepare',
 'ca',
 'final',
 'law',
 'thing',
 'better',
 'special',
 'cares',
 'nose',
 'gets',
 'stuffy',
 'during',
 'night',
 'game',
 'thrones',
 'villain',
 'most',
 'likely',
 'give',
 'mercy',
 'united',
 'states',
 'government',
 'still',
 'blacklist',
 'employment',
 'etc',
 'citizens',
 'because',
 'their',
 'political',
 'views',
 'travel',
 'website',
 'spain',
 'people',
 'think',
 'obama',
 'will',
 'try',
 'take',
 'guns',
 'away',
 'year',
 'old',
 'improve',
 'skills',
 'or',
 'become',
 'entrepreneur',
 'next',
 'few',
 'years',
 'girlfriend',
 'asks',
 'her',
 'boyfriend',
 'did',
 'choose',
 'makes',
 'reply',
 'we',
 'upsc',
 'stall',
 'wings',
 'fully',
 'swept',
 'back',
 'slavs',
 'squat',
 'expect',
 'cognizant',
 'confirmation',
 'mail',
 'month',
 'day',
 'trading',
 'being',
 'kid',
 'rebel',
 'worth',
 'long',
 'run',
 'universities',
 'recruit',
 'new',
 'grads',
 'majors',
 'looking',
 'quickest',
 'instagram',
 'followers',
 'darth',
 'vader',
 'fought',
 'maul',
 'star',
 'wars',
 'legends',
 'stages',
 'breaking',
 'up',
 'between',
 'couple',
 'happens',
 'after',
 'emotionally',
 'whether',
 'its',
 'male',
 'female',
 'examples',
 'products',
 'crude',
 'oil',
 'career',
 'launcher',
 'rbi',
 'grade',
 'b',
 'preparation',
 'blu',
 'ray',
 'play',
 'regular',
 'dvd',
 'player',
 'if',
 'nd',
 'she',
 'always',
 'sad',
 'memorable',
 'have',
 'ever',
 'eaten',
 'gst',
 'affects',
 'cas',
 'tax',
 'officers',
 'difficult',
 'get',
 'into',
 'rsi',
 'who',
 'friend',
 'rap',
 'songs',
 'dance',
 'suddenly',
 'logged',
 'off',
 'gmail',
 'cannot',
 'remember',
 'password',
 'just',
 'realized',
 'recovery',
 'email',
 'no',
 'longer',
 'alive',
 'ways',
 'french',
 'download',
 'content',
 'kickass',
 'torrent',
 'without',
 'registration',
 'normal',
 'dark',
 'ring',
 'around',
 'iris',
 'eye',
 'harry',
 'potter',
 'book',
 'cursed',
 'child',
 'depressed',
 'where',
 'european',
 'family',
 'office',
 'database',
 'java',
 'programming',
 'language',
 'made',
 'store',
 'energy',
 'produced',
 'lightning',
 'review',
 'performance',
 'testing',
 'cost',
 'privacy',
 'as',
 'germany',
 'come',
 'else',
 'lost',
 'gain',
 'types',
 'immunity',
 'narcissistic',
 'personality',
 'disorder',
 'speak',
 'english',
 'fluently',
 'helpful',
 'quickbooks',
 'auto',
 'data',
 'support',
 'phone',
 'number',
 'recover',
 'corrupted',
 'files',
 'richest',
 'gambler',
 'all',
 'reach',
 'his',
 'level',
 'fire',
 'bullet',
 'backward',
 'aircraft',
 'going',
 'faster',
 'than',
 'backwards',
 'prevent',
 'breast',
 'cancer',
 'log',
 'out',
 'account',
 's',
 'purpose',
 'life',
 'bjp',
 'strip',
 'muslims',
 'christians',
 'indian',
 'citizenship',
 'put',
 'them',
 'boats',
 'rohingya',
 'burma',
 'right',
 'etiquette',
 'wishing',
 'jehovah',
 'witness',
 'happy',
 'birthday',
 'wants',
 'open',
 'commercial',
 'fm',
 'radio',
 'station',
 'any',
 'city',
 'procedure',
 'swiss',
 'despise',
 'asians',
 'high',
 'salary',
 'income',
 'jobs',
 'field',
 'biotechnology',
 'height',
 'also',
 'were',
 'major',
 'effects',
 'cambodia',
 'earthquake',
 'these',
 'kamchatca',
 'earthquakes',
 'difference',
 'fairness',
 'gaming',
 'laptop',
 'under',
 'k',
 'inr',
 'warrior',
 'proving',
 'grounds',
 'part',
 'reference',
 'class',
 'th',
 'national',
 'institute',
 'technology',
 'kurukshetra',
 'social',
 'nitk',
 'surathkal',
 'romantic',
 'movies',
 'causes',
 'nightmare',
 'abstract',
 'expressionism',
 'painting',
 'd',
 'printing',
 'work',
 'attend',
 'caltech',
 'jeremy',
 'horcrux',
 'associate',
 'product',
 'manager',
 'apm',
 'programs',
 'early',
 'join',
 'management',
 'rewarding',
 'skype',
 'busy',
 'there',
 'really',
 'war',
 'pakistan',
 'over',
 'uri',
 'attack',
 'ronald',
 'reagan',
 'mannerism',
 'speech',
 'strategies',
 'union',
 'civil',
 'fiction',
 'novel',
 'forgot',
 'recent',
 'demonetisation',
 'results',
 'higher',
 'gdp',
 'heard',
 'hacking',
 'love',
 'pity',
 'competitive',
 'hiring',
 'republic',
 'bank',
 'helps',
 'spam',
 'ranking',
 'adjustment',
 'search',
 'watch',
 'subtitles',
 'usa',
 'powerful',
 'country',
 'world',
 'obtain',
 'instant',
 'ulcer',
 'pain',
 'relief',
 'china',
 'food',
 'taking',
 'advantage',
 'cry',
 'stick',
 'tongues',
 'pictures',
 'ending',
 'depressing',
 'mind',
 'blowing',
 'computer',
 'tools',
 'exist',
 'know',
 'toothbrush',
 'wet',
 'dry',
 'before',
 'applying',
 'toothpaste',
 'question',
 'marked',
 'needing',
 'imrovement',
 'neutral',
 'state',
 'buffer',
 'mineral',
 'holds',
 'highest',
 'electrical',
 'charge',
 'greatest',
 'mystery',
 'universe',
 'alternative',
 'machine',
 'learning',
 'block',
 'sanctions',
 'un',
 'against',
 'jaish',
 'e',
 'mohammad',
 'jem',
 'chief',
 'masood',
 'azhar',
 'future',
 'budget',
 'excessive',
 'amounts',
 'vitamin',
 'c',
 'cause',
 'miscarriage',
 'glass',
 'pay',
 'scale',
 'two',
 'access',
 'torbox',
 'mantras',
 'six',
 'party',
 'talks',
 'successful',
 'register',
 'domain',
 'site',
 'older',
 'men',
 'attracted',
 'young',
 'women',
 'strongest',
 'structure',
 'shape',
 'compression',
 'matter',
 'humans',
 'selfish',
 'evil',
 'endocytosis',
 'active',
 'passive',
 'transport',
 'hair',
 'bald',
 'head',
 'ideal',
 'retirement',
 'our',
 'stance',
 'websites',
 'escorts',
 'polo',
 'diesel',
 'grand',
 'petrol',
 'black',
 'hole',
 'mass',
 'morgan',
 'freeman',
 'correct',
 'he',
 'says',
 'only',
 'stop',
 'racism',
 'talking',
 'currently',
 'offer',
 'employees',
 'stock',
 'options',
 'rsus',
 'distribute',
 'identical',
 'pencils',
 'each',
 'least',
 'pencil',
 'hire',
 'jerry',
 'seinfeld',
 'hours',
 'days',
 'late',
 'rabies',
 'vaccine',
 'possible',
 'non',
 'bite',
 'exposure',
 'britain',
 'ruled',
 'afraid',
 'working',
 'red',
 'keep',
 'keys',
 'age',
 'lose',
 'virginity',
 'could',
 'snoke',
 'secretly',
 'monetize',
 'videos',
 'upload',
 'copyright',
 'then',
 'chances',
 'may',
 'switch',
 'canon',
 'leica',
 'lux',
 'members',
 'moderation',
 'nobody',
 'answer',
 'funniest',
 'joke',
 'got',
 'london',
 '£',
 'pm',
 'deduction',
 'pls',
 'advice',
 'monthly',
 'expenses',
 'saving',
 'stereotypes',
 'kingdom',
 'twitter',
 'business',
 'source',
 'transfer',
 'skrill',
 'paypal',
 'earphone',
 'deep',
 'bass',
 'eligible',
 'sukanya',
 'yojana',
 'forward',
 'engineering',
 'fields',
 'suit',
 'abusing',
 'gross',
 'ctc',
 'towns',
 'kerala',
 'confidence',
 'anyone',
 'see',
 'relation',
 'greek',
 'gods',
 'hindu',
 'apple',
 'music',
 'spotify',
 'fixed',
 'fund',
 'live',
 'cologne',
 'robert',
 'de',
 'niro',
 'al',
 'pacino',
 'more',
 'prefer',
 'small',
 'families',
 'animals',
 'simple',
 'stupid',
 'deleted',
 'chats',
 'addicted',
 'hired',
 'private',
 'ordered',
 'follow',
 'other',
 'startup',
 'accelerator',
 'check',
 'wifi',
 'history',
 'android',
 'phones',
 'significance',
 'battle',
 'somme',
 'this',
 'contrast',
 'rostov',
 'creative',
 'college',
 'admissions',
 'essay',
 'happen',
 'cover',
 'patch',
 'pursue',
 'different',
 'things',
 'ben',
 'affleck',
 'shine',
 'christian',
 'bale',
 'batman',
 'start',
 'hyderabad',
 'possessive',
 'wife',
 'lord',
 'krishna',
 'combination',
 'courses',
 'along',
 'enhance',
 'screenshot',
 'mac',
 'executive',
 'recruiter',
 'psychological',
 'need',
 'collecting',
 'fulfill',
 'must',
 'tv',
 'shows',
 'die',
 'fluent',
 'chinese',
 'demonitization',
 'rupees',
 'notes',
 'real',
 'estate',
 'sector',
 'easiest',
 'billionaire',
 'willing',
 'free',
 'lectures',
 'conduct',
 'workshop',
 'colleges',
 'robotics',
 'hate',
 'hillary',
 'clinton',
 'periods',
 'regarded',
 'unclean',
 'such',
 'prevented',
 'rituals',
 'hinduism',
 'atheism',
 'lack',
 'belief',
 'term',
 'god',
 'jack',
 'dorsey',
 'quotes',
 'lessons',
 'assassin',
 'creed',
 'series',
 'inkjet',
 'printers',
 'color',
 'ink',
 'documents',
 'creativity',
 'important',
 'continue',
 'presidential',
 'campaign',
 'democratic',
 'candidate',
 'headphones',
 'antenna',
 'channels',
 'mobile',
 'companies',
 'install',
 'inbuilt',
 'able',
 'growth',
 'technologies',
 'automation',
 'engineers',
 'apart',
 'disadvantages',
 'listing',
 'nse',
 'derivatives',
 'object',
 'position',
 'respect',
 'continuous',
 'neutron',
 'gpa',
 'enough',
 'top',
 'harvard',
 'profitable',
 'trade',
 'binary',
 'utilize',
 'avoid',
 'depression',
 'security',
 'earn',
 'puk',
 'code',
 'japan',
 'sentences',
 'word',
 'another',
 'billion',
 'dollar',
 'lottery',
 'jackpot',
 'scary',
 'drive',
 'road',
 'hana',
 'given',
 'turns',
 'create',
 'shell',
 'terminal',
 'linux',
 'cognition',
 'affect',
 'perception',
 'tqwl',
 'ckwl',
 'tatkal',
 'waiting',
 'list',
 'generations',
 'champions',
 'league',
 'drinking',
 'liters',
 'unhealthy',
 'great',
 'lakes',
 'wildlife',
 'lake',
 'porn',
 'stars',
 'supporters',
 'feel',
 'walking',
 'promises',
 'worried',
 'others',
 'opinions',
 'potty',
 'train',
 'months',
 'pitbull',
 'jump',
 'rope',
 'five',
 'minutes',
 'calories',
 'test',
 'gate',
 'cs',
 'stream',
 'material',
 'understanding',
 'algorithmic',
 'analysis',
 ...]

In [42]:
# generate index of all the words
word2idx = {w:i for i,w in enumerate(vocab)}
word2idx

{'<pad>': 0,
 '<unk>': 1,
 'what': 2,
 'is': 3,
 'the': 4,
 'step': 5,
 'by': 6,
 'guide': 7,
 'to': 8,
 'invest': 9,
 'in': 10,
 'share': 11,
 'market': 12,
 'india': 13,
 'story': 14,
 'of': 15,
 'kohinoor': 16,
 'koh': 17,
 'i': 18,
 'noor': 19,
 'diamond': 20,
 'how': 21,
 'can': 22,
 'increase': 23,
 'speed': 24,
 'my': 25,
 'internet': 26,
 'connection': 27,
 'while': 28,
 'using': 29,
 'a': 30,
 'vpn': 31,
 'why': 32,
 'am': 33,
 'mentally': 34,
 'very': 35,
 'lonely': 36,
 'solve': 37,
 'it': 38,
 'which': 39,
 'one': 40,
 'dissolve': 41,
 'water': 42,
 'sugar': 43,
 'salt': 44,
 'methane': 45,
 'and': 46,
 'carbon': 47,
 'di': 48,
 'oxide': 49,
 'astrology': 50,
 'capricorn': 51,
 'sun': 52,
 'cap': 53,
 'moon': 54,
 'rising': 55,
 'does': 56,
 'that': 57,
 'say': 58,
 'about': 59,
 'me': 60,
 'should': 61,
 'buy': 62,
 'tiago': 63,
 'be': 64,
 'good': 65,
 'geologist': 66,
 'when': 67,
 'do': 68,
 'you': 69,
 'use': 70,
 'instead': 71,
 'motorola': 72,
 'company': 73,
 'hack': 74,
 'charter': 75,
 'method': 76,
 'find': 77,
 'separation': 78,
 'slits': 79,
 'fresnel': 80,
 'read': 81,
 'youtube': 82,
 'comments': 83,
 'make': 84,
 'physics': 85,
 'easy': 86,
 'learn': 87,
 'was': 88,
 'your': 89,
 'first': 90,
 'sexual': 91,
 'experience': 92,
 'like': 93,
 'are': 94,
 'laws': 95,
 'change': 96,
 'status': 97,
 'from': 98,
 'student': 99,
 'visa': 100,
 'green': 101,
 'card': 102,
 'us': 103,
 'they': 104,
 'compare': 105,
 'immigration': 106,
 'canada': 107,
 'would': 108,
 'trump': 109,
 'presidency': 110,
 'mean': 111,
 'for': 112,
 'current': 113,
 'international': 114,
 'master’s': 115,
 'students': 116,
 'on': 117,
 'an': 118,
 'f': 119,
 'manipulation': 120,
 'girls': 121,
 'want': 122,
 'friends': 123,
 'with': 124,
 'guy': 125,
 'reject': 126,
 'so': 127,
 'many': 128,
 'quora': 129,
 'users': 130,
 'posting': 131,
 'questions': 132,
 'readily': 133,
 'answered': 134,
 'google': 135,
 'best': 136,
 'digital': 137,
 'marketing': 138,
 'institution': 139,
 'banglore': 140,
 'rockets': 141,
 'look': 142,
 'white': 143,
 'causing': 144,
 'someone': 145,
 'jealous': 146,
 'not': 147,
 'ask': 148,
 'much': 149,
 'kv': 150,
 'hp': 151,
 'every': 152,
 'tears': 153,
 'eyes': 154,
 'at': 155,
 'clock': 156,
 'numbers': 157,
 'same': 158,
 'some': 159,
 'tips': 160,
 'making': 161,
 'through': 162,
 'job': 163,
 'interview': 164,
 'process': 165,
 'medicines': 166,
 'web': 167,
 'application': 168,
 'society': 169,
 'place': 170,
 'too': 171,
 'importance': 172,
 'sports': 173,
 'way': 174,
 'money': 175,
 'online': 176,
 'prepare': 177,
 'ca': 178,
 'final': 179,
 'law': 180,
 'thing': 181,
 'better': 182,
 'special': 183,
 'cares': 184,
 'nose': 185,
 'gets': 186,
 'stuffy': 187,
 'during': 188,
 'night': 189,
 'game': 190,
 'thrones': 191,
 'villain': 192,
 'most': 193,
 'likely': 194,
 'give': 195,
 'mercy': 196,
 'united': 197,
 'states': 198,
 'government': 199,
 'still': 200,
 'blacklist': 201,
 'employment': 202,
 'etc': 203,
 'citizens': 204,
 'because': 205,
 'their': 206,
 'political': 207,
 'views': 208,
 'travel': 209,
 'website': 210,
 'spain': 211,
 'people': 212,
 'think': 213,
 'obama': 214,
 'will': 215,
 'try': 216,
 'take': 217,
 'guns': 218,
 'away': 219,
 'year': 220,
 'old': 221,
 'improve': 222,
 'skills': 223,
 'or': 224,
 'become': 225,
 'entrepreneur': 226,
 'next': 227,
 'few': 228,
 'years': 229,
 'girlfriend': 230,
 'asks': 231,
 'her': 232,
 'boyfriend': 233,
 'did': 234,
 'choose': 235,
 'makes': 236,
 'reply': 237,
 'we': 238,
 'upsc': 239,
 'stall': 240,
 'wings': 241,
 'fully': 242,
 'swept': 243,
 'back': 244,
 'slavs': 245,
 'squat': 246,
 'expect': 247,
 'cognizant': 248,
 'confirmation': 249,
 'mail': 250,
 'month': 251,
 'day': 252,
 'trading': 253,
 'being': 254,
 'kid': 255,
 'rebel': 256,
 'worth': 257,
 'long': 258,
 'run': 259,
 'universities': 260,
 'recruit': 261,
 'new': 262,
 'grads': 263,
 'majors': 264,
 'looking': 265,
 'quickest': 266,
 'instagram': 267,
 'followers': 268,
 'darth': 269,
 'vader': 270,
 'fought': 271,
 'maul': 272,
 'star': 273,
 'wars': 274,
 'legends': 275,
 'stages': 276,
 'breaking': 277,
 'up': 278,
 'between': 279,
 'couple': 280,
 'happens': 281,
 'after': 282,
 'emotionally': 283,
 'whether': 284,
 'its': 285,
 'male': 286,
 'female': 287,
 'examples': 288,
 'products': 289,
 'crude': 290,
 'oil': 291,
 'career': 292,
 'launcher': 293,
 'rbi': 294,
 'grade': 295,
 'b': 296,
 'preparation': 297,
 'blu': 298,
 'ray': 299,
 'play': 300,
 'regular': 301,
 'dvd': 302,
 'player': 303,
 'if': 304,
 'nd': 305,
 'she': 306,
 'always': 307,
 'sad': 308,
 'memorable': 309,
 'have': 310,
 'ever': 311,
 'eaten': 312,
 'gst': 313,
 'affects': 314,
 'cas': 315,
 'tax': 316,
 'officers': 317,
 'difficult': 318,
 'get': 319,
 'into': 320,
 'rsi': 321,
 'who': 322,
 'friend': 323,
 'rap': 324,
 'songs': 325,
 'dance': 326,
 'suddenly': 327,
 'logged': 328,
 'off': 329,
 'gmail': 330,
 'cannot': 331,
 'remember': 332,
 'password': 333,
 'just': 334,
 'realized': 335,
 'recovery': 336,
 'email': 337,
 'no': 338,
 'longer': 339,
 'alive': 340,
 'ways': 341,
 'french': 342,
 'download': 343,
 'content': 344,
 'kickass': 345,
 'torrent': 346,
 'without': 347,
 'registration': 348,
 'normal': 349,
 'dark': 350,
 'ring': 351,
 'around': 352,
 'iris': 353,
 'eye': 354,
 'harry': 355,
 'potter': 356,
 'book': 357,
 'cursed': 358,
 'child': 359,
 'depressed': 360,
 'where': 361,
 'european': 362,
 'family': 363,
 'office': 364,
 'database': 365,
 'java': 366,
 'programming': 367,
 'language': 368,
 'made': 369,
 'store': 370,
 'energy': 371,
 'produced': 372,
 'lightning': 373,
 'review': 374,
 'performance': 375,
 'testing': 376,
 'cost': 377,
 'privacy': 378,
 'as': 379,
 'germany': 380,
 'come': 381,
 'else': 382,
 'lost': 383,
 'gain': 384,
 'types': 385,
 'immunity': 386,
 'narcissistic': 387,
 'personality': 388,
 'disorder': 389,
 'speak': 390,
 'english': 391,
 'fluently': 392,
 'helpful': 393,
 'quickbooks': 394,
 'auto': 395,
 'data': 396,
 'support': 397,
 'phone': 398,
 'number': 399,
 'recover': 400,
 'corrupted': 401,
 'files': 402,
 'richest': 403,
 'gambler': 404,
 'all': 405,
 'reach': 406,
 'his': 407,
 'level': 408,
 'fire': 409,
 'bullet': 410,
 'backward': 411,
 'aircraft': 412,
 'going': 413,
 'faster': 414,
 'than': 415,
 'backwards': 416,
 'prevent': 417,
 'breast': 418,
 'cancer': 419,
 'log': 420,
 'out': 421,
 'account': 422,
 's': 423,
 'purpose': 424,
 'life': 425,
 'bjp': 426,
 'strip': 427,
 'muslims': 428,
 'christians': 429,
 'indian': 430,
 'citizenship': 431,
 'put': 432,
 'them': 433,
 'boats': 434,
 'rohingya': 435,
 'burma': 436,
 'right': 437,
 'etiquette': 438,
 'wishing': 439,
 'jehovah': 440,
 'witness': 441,
 'happy': 442,
 'birthday': 443,
 'wants': 444,
 'open': 445,
 'commercial': 446,
 'fm': 447,
 'radio': 448,
 'station': 449,
 'any': 450,
 'city': 451,
 'procedure': 452,
 'swiss': 453,
 'despise': 454,
 'asians': 455,
 'high': 456,
 'salary': 457,
 'income': 458,
 'jobs': 459,
 'field': 460,
 'biotechnology': 461,
 'height': 462,
 'also': 463,
 'were': 464,
 'major': 465,
 'effects': 466,
 'cambodia': 467,
 'earthquake': 468,
 'these': 469,
 'kamchatca': 470,
 'earthquakes': 471,
 'difference': 472,
 'fairness': 473,
 'gaming': 474,
 'laptop': 475,
 'under': 476,
 'k': 477,
 'inr': 478,
 'warrior': 479,
 'proving': 480,
 'grounds': 481,
 'part': 482,
 'reference': 483,
 'class': 484,
 'th': 485,
 'national': 486,
 'institute': 487,
 'technology': 488,
 'kurukshetra': 489,
 'social': 490,
 'nitk': 491,
 'surathkal': 492,
 'romantic': 493,
 'movies': 494,
 'causes': 495,
 'nightmare': 496,
 'abstract': 497,
 'expressionism': 498,
 'painting': 499,
 'd': 500,
 'printing': 501,
 'work': 502,
 'attend': 503,
 'caltech': 504,
 'jeremy': 505,
 'horcrux': 506,
 'associate': 507,
 'product': 508,
 'manager': 509,
 'apm': 510,
 'programs': 511,
 'early': 512,
 'join': 513,
 'management': 514,
 'rewarding': 515,
 'skype': 516,
 'busy': 517,
 'there': 518,
 'really': 519,
 'war': 520,
 'pakistan': 521,
 'over': 522,
 'uri': 523,
 'attack': 524,
 'ronald': 525,
 'reagan': 526,
 'mannerism': 527,
 'speech': 528,
 'strategies': 529,
 'union': 530,
 'civil': 531,
 'fiction': 532,
 'novel': 533,
 'forgot': 534,
 'recent': 535,
 'demonetisation': 536,
 'results': 537,
 'higher': 538,
 'gdp': 539,
 'heard': 540,
 'hacking': 541,
 'love': 542,
 'pity': 543,
 'competitive': 544,
 'hiring': 545,
 'republic': 546,
 'bank': 547,
 'helps': 548,
 'spam': 549,
 'ranking': 550,
 'adjustment': 551,
 'search': 552,
 'watch': 553,
 'subtitles': 554,
 'usa': 555,
 'powerful': 556,
 'country': 557,
 'world': 558,
 'obtain': 559,
 'instant': 560,
 'ulcer': 561,
 'pain': 562,
 'relief': 563,
 'china': 564,
 'food': 565,
 'taking': 566,
 'advantage': 567,
 'cry': 568,
 'stick': 569,
 'tongues': 570,
 'pictures': 571,
 'ending': 572,
 'depressing': 573,
 'mind': 574,
 'blowing': 575,
 'computer': 576,
 'tools': 577,
 'exist': 578,
 'know': 579,
 'toothbrush': 580,
 'wet': 581,
 'dry': 582,
 'before': 583,
 'applying': 584,
 'toothpaste': 585,
 'question': 586,
 'marked': 587,
 'needing': 588,
 'imrovement': 589,
 'neutral': 590,
 'state': 591,
 'buffer': 592,
 'mineral': 593,
 'holds': 594,
 'highest': 595,
 'electrical': 596,
 'charge': 597,
 'greatest': 598,
 'mystery': 599,
 'universe': 600,
 'alternative': 601,
 'machine': 602,
 'learning': 603,
 'block': 604,
 'sanctions': 605,
 'un': 606,
 'against': 607,
 'jaish': 608,
 'e': 609,
 'mohammad': 610,
 'jem': 611,
 'chief': 612,
 'masood': 613,
 'azhar': 614,
 'future': 615,
 'budget': 616,
 'excessive': 617,
 'amounts': 618,
 'vitamin': 619,
 'c': 620,
 'cause': 621,
 'miscarriage': 622,
 'glass': 623,
 'pay': 624,
 'scale': 625,
 'two': 626,
 'access': 627,
 'torbox': 628,
 'mantras': 629,
 'six': 630,
 'party': 631,
 'talks': 632,
 'successful': 633,
 'register': 634,
 'domain': 635,
 'site': 636,
 'older': 637,
 'men': 638,
 'attracted': 639,
 'young': 640,
 'women': 641,
 'strongest': 642,
 'structure': 643,
 'shape': 644,
 'compression': 645,
 'matter': 646,
 'humans': 647,
 'selfish': 648,
 'evil': 649,
 'endocytosis': 650,
 'active': 651,
 'passive': 652,
 'transport': 653,
 'hair': 654,
 'bald': 655,
 'head': 656,
 'ideal': 657,
 'retirement': 658,
 'our': 659,
 'stance': 660,
 'websites': 661,
 'escorts': 662,
 'polo': 663,
 'diesel': 664,
 'grand': 665,
 'petrol': 666,
 'black': 667,
 'hole': 668,
 'mass': 669,
 'morgan': 670,
 'freeman': 671,
 'correct': 672,
 'he': 673,
 'says': 674,
 'only': 675,
 'stop': 676,
 'racism': 677,
 'talking': 678,
 'currently': 679,
 'offer': 680,
 'employees': 681,
 'stock': 682,
 'options': 683,
 'rsus': 684,
 'distribute': 685,
 'identical': 686,
 'pencils': 687,
 'each': 688,
 'least': 689,
 'pencil': 690,
 'hire': 691,
 'jerry': 692,
 'seinfeld': 693,
 'hours': 694,
 'days': 695,
 'late': 696,
 'rabies': 697,
 'vaccine': 698,
 'possible': 699,
 'non': 700,
 'bite': 701,
 'exposure': 702,
 'britain': 703,
 'ruled': 704,
 'afraid': 705,
 'working': 706,
 'red': 707,
 'keep': 708,
 'keys': 709,
 'age': 710,
 'lose': 711,
 'virginity': 712,
 'could': 713,
 'snoke': 714,
 'secretly': 715,
 'monetize': 716,
 'videos': 717,
 'upload': 718,
 'copyright': 719,
 'then': 720,
 'chances': 721,
 'may': 722,
 'switch': 723,
 'canon': 724,
 'leica': 725,
 'lux': 726,
 'members': 727,
 'moderation': 728,
 'nobody': 729,
 'answer': 730,
 'funniest': 731,
 'joke': 732,
 'got': 733,
 'london': 734,
 '£': 735,
 'pm': 736,
 'deduction': 737,
 'pls': 738,
 'advice': 739,
 'monthly': 740,
 'expenses': 741,
 'saving': 742,
 'stereotypes': 743,
 'kingdom': 744,
 'twitter': 745,
 'business': 746,
 'source': 747,
 'transfer': 748,
 'skrill': 749,
 'paypal': 750,
 'earphone': 751,
 'deep': 752,
 'bass': 753,
 'eligible': 754,
 'sukanya': 755,
 'yojana': 756,
 'forward': 757,
 'engineering': 758,
 'fields': 759,
 'suit': 760,
 'abusing': 761,
 'gross': 762,
 'ctc': 763,
 'towns': 764,
 'kerala': 765,
 'confidence': 766,
 'anyone': 767,
 'see': 768,
 'relation': 769,
 'greek': 770,
 'gods': 771,
 'hindu': 772,
 'apple': 773,
 'music': 774,
 'spotify': 775,
 'fixed': 776,
 'fund': 777,
 'live': 778,
 'cologne': 779,
 'robert': 780,
 'de': 781,
 'niro': 782,
 'al': 783,
 'pacino': 784,
 'more': 785,
 'prefer': 786,
 'small': 787,
 'families': 788,
 'animals': 789,
 'simple': 790,
 'stupid': 791,
 'deleted': 792,
 'chats': 793,
 'addicted': 794,
 'hired': 795,
 'private': 796,
 'ordered': 797,
 'follow': 798,
 'other': 799,
 'startup': 800,
 'accelerator': 801,
 'check': 802,
 'wifi': 803,
 'history': 804,
 'android': 805,
 'phones': 806,
 'significance': 807,
 'battle': 808,
 'somme': 809,
 'this': 810,
 'contrast': 811,
 'rostov': 812,
 'creative': 813,
 'college': 814,
 'admissions': 815,
 'essay': 816,
 'happen': 817,
 'cover': 818,
 'patch': 819,
 'pursue': 820,
 'different': 821,
 'things': 822,
 'ben': 823,
 'affleck': 824,
 'shine': 825,
 'christian': 826,
 'bale': 827,
 'batman': 828,
 'start': 829,
 'hyderabad': 830,
 'possessive': 831,
 'wife': 832,
 'lord': 833,
 'krishna': 834,
 'combination': 835,
 'courses': 836,
 'along': 837,
 'enhance': 838,
 'screenshot': 839,
 'mac': 840,
 'executive': 841,
 'recruiter': 842,
 'psychological': 843,
 'need': 844,
 'collecting': 845,
 'fulfill': 846,
 'must': 847,
 'tv': 848,
 'shows': 849,
 'die': 850,
 'fluent': 851,
 'chinese': 852,
 'demonitization': 853,
 'rupees': 854,
 'notes': 855,
 'real': 856,
 'estate': 857,
 'sector': 858,
 'easiest': 859,
 'billionaire': 860,
 'willing': 861,
 'free': 862,
 'lectures': 863,
 'conduct': 864,
 'workshop': 865,
 'colleges': 866,
 'robotics': 867,
 'hate': 868,
 'hillary': 869,
 'clinton': 870,
 'periods': 871,
 'regarded': 872,
 'unclean': 873,
 'such': 874,
 'prevented': 875,
 'rituals': 876,
 'hinduism': 877,
 'atheism': 878,
 'lack': 879,
 'belief': 880,
 'term': 881,
 'god': 882,
 'jack': 883,
 'dorsey': 884,
 'quotes': 885,
 'lessons': 886,
 'assassin': 887,
 'creed': 888,
 'series': 889,
 'inkjet': 890,
 'printers': 891,
 'color': 892,
 'ink': 893,
 'documents': 894,
 'creativity': 895,
 'important': 896,
 'continue': 897,
 'presidential': 898,
 'campaign': 899,
 'democratic': 900,
 'candidate': 901,
 'headphones': 902,
 'antenna': 903,
 'channels': 904,
 'mobile': 905,
 'companies': 906,
 'install': 907,
 'inbuilt': 908,
 'able': 909,
 'growth': 910,
 'technologies': 911,
 'automation': 912,
 'engineers': 913,
 'apart': 914,
 'disadvantages': 915,
 'listing': 916,
 'nse': 917,
 'derivatives': 918,
 'object': 919,
 'position': 920,
 'respect': 921,
 'continuous': 922,
 'neutron': 923,
 'gpa': 924,
 'enough': 925,
 'top': 926,
 'harvard': 927,
 'profitable': 928,
 'trade': 929,
 'binary': 930,
 'utilize': 931,
 'avoid': 932,
 'depression': 933,
 'security': 934,
 'earn': 935,
 'puk': 936,
 'code': 937,
 'japan': 938,
 'sentences': 939,
 'word': 940,
 'another': 941,
 'billion': 942,
 'dollar': 943,
 'lottery': 944,
 'jackpot': 945,
 'scary': 946,
 'drive': 947,
 'road': 948,
 'hana': 949,
 'given': 950,
 'turns': 951,
 'create': 952,
 'shell': 953,
 'terminal': 954,
 'linux': 955,
 'cognition': 956,
 'affect': 957,
 'perception': 958,
 'tqwl': 959,
 'ckwl': 960,
 'tatkal': 961,
 'waiting': 962,
 'list': 963,
 'generations': 964,
 'champions': 965,
 'league': 966,
 'drinking': 967,
 'liters': 968,
 'unhealthy': 969,
 'great': 970,
 'lakes': 971,
 'wildlife': 972,
 'lake': 973,
 'porn': 974,
 'stars': 975,
 'supporters': 976,
 'feel': 977,
 'walking': 978,
 'promises': 979,
 'worried': 980,
 'others': 981,
 'opinions': 982,
 'potty': 983,
 'train': 984,
 'months': 985,
 'pitbull': 986,
 'jump': 987,
 'rope': 988,
 'five': 989,
 'minutes': 990,
 'calories': 991,
 'test': 992,
 'gate': 993,
 'cs': 994,
 'stream': 995,
 'material': 996,
 'understanding': 997,
 'algorithmic': 998,
 'analysis': 999,
 ...}

In [43]:
VOCAB_SIZE = len(vocab)
VOCAB_SIZE

32980

In [44]:
# tokenize a text --> consider upto first 25 words only
# if there are <25 words, append zeros at the end to make 25 words exactly
def encode(sent, max_words=25):
    # in word2idx.get(w,1) --> if w doesn't exist in vocab, return index 1 <'unk'>
    ids = [word2idx.get(w,1) for w in tokenize(sent)][:max_words]
    # append 0 at the end, 0=<'pad'> to make the length 25 exactly
    ids += [0] * (max_words - len(ids))
    return ids

In [45]:
MAX_WORDS = 30
df_train['question1'] = df_train['question1'].apply(lambda s: encode(s, MAX_WORDS))
df_train['question2'] = df_train['question2'].apply(lambda s: encode(s, MAX_WORDS))
df_train

,question1,question2,is_duplicate
0,"[2, 3, 4, 5, 6, 5, 7, 8, 9, 10, 11, 12, 10, 13...","[2, 3, 4, 5, 6, 5, 7, 8, 9, 10, 11, 12, 0, 0, ...",0
1,"[2, 3, 4, 14, 15, 16, 17, 18, 19, 20, 0, 0, 0,...","[2, 108, 817, 304, 4, 430, 199, 4275, 4, 16, 1...",0
2,"[21, 22, 18, 23, 4, 24, 15, 25, 26, 27, 28, 29...","[21, 22, 26, 24, 64, 1741, 6, 541, 162, 27538,...",0
3,"[32, 33, 18, 34, 35, 36, 21, 22, 18, 37, 38, 0...","[77, 4, 9718, 67, 1356, 1356, 3, 11189, 6, 0, ...",0
4,"[39, 40, 41, 10, 42, 1, 43, 44, 45, 46, 47, 48...","[39, 3012, 108, 5313, 10, 44, 42, 0, 0, 0, 0, ...",0
...,...,...,...
403963,"[21, 128, 2510, 94, 518, 10, 4, 16286, 367, 36...","[21, 128, 2510, 94, 518, 10, 8483, 367, 368, 1...",0
403964,"[68, 69, 1659, 518, 3, 425, 282, 1246, 0, 0, 0...","[3, 38, 1484, 57, 518, 3, 425, 282, 1246, 0, 0...",1
403965,"[2, 3, 40, 7787, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[2, 3, 810, 7787, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",0
403966,"[2, 3, 4, 14380, 10367, 377, 15, 2188, 28, 240...","[18, 33, 2145, 3855, 1962, 1790, 1110, 18, 122...",0
403967,"[2, 3, 93, 8, 310, 1726, 124, 5106, 0, 0, 0, 0...","[2, 3, 38, 93, 8, 310, 1726, 124, 89, 5106, 0,...",0

In [46]:
# Skip-gram Word2Vec with negative sampling (using custom nn.Module on GPU)

WINDOW = 4
EMBED_DIM = 128
NEG_SAMPLES = 5

In [ ]:
def build_skipgram_pairs(token_list, window=WINDOW):
    pairs = []
    for tokens in token_list: